apiVersion: v2
name: basechart
description: A Helm chart for Kubernetes applications
type: application
version: 1.0.0
appVersion: "1.0.0"
icon: https://helm.sh/img/helm.svg # เพิ่ม icon เพื่อแก้ warning

dependencies:
  - name: "basechart"
    repository: "https://raw.githubusercontent.com/[your-username]/helm-charts/main/"
    version: 1.0.0