apiVersion: v2
name: basechart
description: A Helm chart for Kubernetes applications
type: application
version: 1.0.1
appVersion: "1.0.0"
icon: https://helm.sh/img/helm.svg # เพิ่ม icon เพื่อแก้ warning
dependencies:
  - name: "basechart"
    repository: "https://lbxheng.github.io/helmcharts"
    version: 1.0.1